#!/usr/bin/env bash
# Creates RSA key pair with passphrase protection

# Generate the key pair in the current directory
ssh-keygen -t rsa -b 4096 -f school -N "betty" -q <<<y >/dev/null 2>&1

# Display the output messages
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in school."
echo "Your public key has been saved in school.pub."
echo "The key fingerprint is:"
ssh-keygen -lf school | cut -d' ' -f2-
echo "The key's randomart image is:"
ssh-keygen -lvf school -E md5 | grep -A 16 "^+"

